export const openProfileBtn = document.querySelector('.profile__create-btn');
export const createCardBtn = document.querySelector('.profile__add-btn');
export  const profileName = document.querySelector('.profile__title');
export  const profileJob = document.querySelector('.profile__subtitle');
const popupProfile = document.querySelector('.popup-profile');
export const avatarImage = document.querySelector('.profile__avatar')
export const avatar = document.querySelector('.profile__image-hover')
export   const nameInput = popupProfile.querySelector('.popup__input_type_name');
export  const jobInput = popupProfile.querySelector('.popup__input_type_job');
export  const template = document.querySelector('#card').content.querySelector('.element');